cursor #fce8c3
background #0e0d0b
selection_foreground #0e0d0b

active_border_color #fce8c3
inactive_border_color #323232

active_tab_font_style   bold

active_tab_foreground   #fce8c3
inactive_tab_foreground #9f8c6a

visual_bell_color #3f2f0e

window_title_bar_active_foreground   #1a1a1a
window_title_bar_active_background   #9f8c6a
window_title_bar_inactive_foreground none
window_title_bar_inactive_background none
